[package]
name = "faux_macros"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "1.0.3", features = ["full", "extra-traits"] }
quote = "1.0.2"
proc-macro2 = "1.0.1"
faux = { path = "../"}

[lib]
proc-macro = true
